### ISSUE TITLE
insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by 007joshie** [finncodes/iptv#2]
Hey, not sure if you were aware of this but on the link provided, an error occurred as pasted below. I would really appreciate if you were able to give any fix/advice on this issue. 

xhr-loader.js:82 Mixed Content: The page at 'https://freeview-nz.netlify.app/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://i.mjh.nz/nz/tv.9.m3u8'. This request has been blocked; the content must be served over HTTPS.

**Comment by finncodes** [comment]
Hi @007joshie, I just fixed this with commit 4bc8c87. Let me know if it is or isn't working for you 🙂

**Comment by 007joshie** [comment]
Cheers, Thank you so much. I look forward to using this as we don't have cable.
